#! /usr/bin/env python3

import sys
import os
import re
from urllib.parse import urlparse


def shebang(language):
    language = language.lower()
    SHEBANGS = {
        "python": "#! /usr/bin/env python3",
        "ruby": "#! /usr/bin/env ruby",
        "golang": '///usr/bin/true; exec /usr/bin/env go run "$0" "$@"',
    }
    return f"{SHEBANGS.get(language, '')}"


def extension(language):
    language = language.lower()
    EXTENSIONS = {"python": "py", "ruby": "rb", "golang": "go"}

    return EXTENSIONS[language]


raw_problem_url = input("Enter problem URL: ")
problem_url = urlparse(raw_problem_url)

if "leetcode" in problem_url.hostname:
    site = "leetcode"
elif "hackerrank" in problem_url.hostname:
    site = "hackerrank"

if site not in os.listdir():
    os.mkdir(site)

raw_problem_name = re.search("/\w+-.*/", problem_url.path).group()
problem_name = " ".join(
    [i[0].upper() + i[1:] for i in re.findall("\w+", raw_problem_name)]
)
problem_dir_name = raw_problem_name.replace("/", "").replace("-", "_")

if problem_dir_name not in os.listdir(site):
    os.mkdir(os.path.join(site, problem_dir_name))
    with open(os.path.join(site, problem_dir_name, "README.md"), "w") as f:

        f.write(f"# {problem_name}\n")
        f.write(f"Problem URL: {raw_problem_url}")

language = input(
    "What language are you adding your solution in? (For ex: Python, Ruby, Golang etc): "
)
github_username = input("What's your GitHub username: ")

filename = f"{github_username}.{extension(language)}"
filename_with_path = os.path.join(site, problem_dir_name, filename)

if filename in os.listdir(os.path.join(site, problem_dir_name)):
    print("Looks like you already solved this problem!")
    sys.exit(0)
with open(filename_with_path, "w") as g:
    g.write(shebang(language))
